import { DEFAULT_COMMUNITY, mapRegionFor, offsetFrom } from '@/lib/community';
import type { HelpRequest, LatLng, Partner, User } from '@/types/barakah';

/**
 * Seed community.
 *
 * Everything here is positioned relative to the community anchor rather than
 * to a fixed address, so the same seed drops into any city the app is opened
 * in. The names are generic on purpose: Barakah is not affiliated with any
 * particular masjid, organisation or business, and shipping a real one's name
 * in the demo data would imply otherwise.
 */

export const ANCHOR: LatLng = DEFAULT_COMMUNITY.anchor;
export const MAP_REGION = mapRegionFor(ANCHOR);

export const DEFAULT_USER_ID = 'user-you';

export const partners: Partner[] = [
  {
    id: 'partner-institution',
    name: DEFAULT_COMMUNITY.institutionName,
    type: 'institution',
    categories: ['childcare', 'ride', 'food', 'elder_transport', 'other'],
    location: ANCHOR,
    standingOffer: 'Vetted volunteer roster. Absorbs requests no neighbour can take.',
    isEscalationPartner: true,
  },
  {
    id: 'partner-grocer',
    name: DEFAULT_COMMUNITY.businessName,
    type: 'business',
    categories: ['food'],
    location: offsetFrom(ANCHOR, -0.0042, -0.0075),
    standingOffer: 'Friday pantry pickup. Bags ready after Asr.',
  },
];

export const users: User[] = [
  {
    id: DEFAULT_USER_ID,
    // The person holding the phone. Editable in Profile — the demo should not
    // put words, or a name, in the presenter's mouth.
    name: 'You',
    phone: '+1 (555) 010-0142',
    email: null,
    trustTier: 2,
    categoriesOffered: ['ride', 'food'],
    location: offsetFrom(ANCHOR, 0.0026, -0.0034),
    ratingAvg: 4.9,
    ratingCount: 12,
    points: 80,
    completedHelps: 7,
    responseRate: 0.92,
    lastMatchAt: '2026-09-01T14:00:00Z',
    partnerId: null,
    avatarColor: '#0F766E',
    isNewHelper: false,
    verificationStatus: 'approved',
    availabilityLabel: 'Evenings & Friday midday',
    radiusMiles: 5,
  },
  {
    id: 'user-omar',
    name: 'Omar Hassan',
    phone: '+1 (555) 010-0198',
    email: null,
    trustTier: 2,
    categoriesOffered: ['ride', 'food', 'moving_help', 'other'],
    location: offsetFrom(ANCHOR, 0.0058, -0.0042),
    ratingAvg: 4.8,
    ratingCount: 28,
    points: 240,
    completedHelps: 26,
    responseRate: 0.95,
    lastMatchAt: '2026-09-04T18:00:00Z',
    partnerId: null,
    avatarColor: '#115E59',
    isNewHelper: false,
    verificationStatus: 'approved',
    availabilityLabel: 'Weekday afternoons & Jummah',
    radiusMiles: 6,
  },
  {
    id: 'user-fatima',
    name: 'Fatima Ali',
    phone: '+1 (555) 010-0110',
    email: null,
    trustTier: 3,
    categoriesOffered: ['childcare', 'ride', 'food', 'elder_transport'],
    location: offsetFrom(ANCHOR, -0.0065, 0.0052),
    ratingAvg: 5.0,
    ratingCount: 41,
    points: 0,
    completedHelps: 40,
    responseRate: 0.98,
    lastMatchAt: '2026-09-03T12:00:00Z',
    partnerId: 'partner-institution',
    avatarColor: '#15803D',
    isNewHelper: false,
    verificationStatus: 'approved',
    availabilityLabel: 'Partner volunteer roster',
    radiusMiles: 8,
  },
  {
    id: 'user-yusuf',
    name: 'Yusuf Khan',
    phone: '+1 (555) 010-0166',
    email: null,
    trustTier: 2,
    categoriesOffered: ['food', 'laptop'],
    location: offsetFrom(ANCHOR, 0.0031, 0.0104),
    ratingAvg: null,
    ratingCount: 0,
    points: 0,
    completedHelps: 0,
    responseRate: 1,
    lastMatchAt: null,
    partnerId: 'partner-grocer',
    avatarColor: '#B45309',
    isNewHelper: true,
    verificationStatus: 'approved',
    availabilityLabel: 'Store hours',
    radiusMiles: 4,
  },
  {
    id: 'user-mariam',
    name: 'Mariam Noor',
    phone: '+1 (555) 010-0133',
    email: null,
    trustTier: 2,
    categoriesOffered: ['ride', 'moving_help', 'other'],
    location: offsetFrom(ANCHOR, -0.0088, -0.0031),
    ratingAvg: 4.6,
    ratingCount: 9,
    points: 90,
    completedHelps: 9,
    responseRate: 0.88,
    lastMatchAt: '2026-08-28T10:00:00Z',
    partnerId: null,
    avatarColor: '#0E7490',
    isNewHelper: false,
    verificationStatus: 'approved',
    availabilityLabel: 'Weekends',
    radiusMiles: 5,
  },
  {
    id: 'user-ibrahim',
    name: 'Ibrahim Saleh',
    phone: '+1 (555) 010-0177',
    email: null,
    trustTier: 2,
    categoriesOffered: ['ride', 'food', 'new_muslim_resources'],
    location: offsetFrom(ANCHOR, 0.0097, 0.0068),
    ratingAvg: 4.7,
    ratingCount: 15,
    points: 150,
    completedHelps: 15,
    responseRate: 0.9,
    lastMatchAt: '2026-09-02T09:00:00Z',
    partnerId: null,
    avatarColor: '#047857',
    isNewHelper: false,
    verificationStatus: 'approved',
    availabilityLabel: 'Mornings',
    radiusMiles: 7,
  },
];

export const seedRequests: HelpRequest[] = [
  {
    id: 'req-jummah',
    requesterId: 'user-seed-1',
    rawText: 'Need a ride to Jummah tomorrow around 1pm, near the masjid',
    category: 'ride',
    urgency: 'scheduled',
    timeWindow: 'tomorrow 1pm-2pm',
    locationText: 'Near the masjid',
    preference: null,
    confidence: 0.94,
    location: offsetFrom(ANCHOR, 0.0044, 0.0081),
    status: 'open',
    matchedHelperId: null,
    aiMatchReason: null,
    createdAt: '2026-09-05T14:00:00Z',
    requesterConfirmed: false,
    helperConfirmed: false,
    customLabel: null,
  },
  {
    id: 'req-food',
    requesterId: 'user-seed-2',
    rawText: 'Could use groceries this evening, family of 4',
    category: 'food',
    urgency: 'immediate',
    timeWindow: 'this evening',
    locationText: 'Near the main road',
    preference: null,
    confidence: 0.9,
    location: offsetFrom(ANCHOR, -0.0051, 0.0093),
    status: 'open',
    matchedHelperId: null,
    aiMatchReason: null,
    createdAt: '2026-09-05T15:30:00Z',
    requesterConfirmed: false,
    helperConfirmed: false,
    customLabel: null,
  },
  {
    id: 'req-appointment',
    requesterId: 'user-seed-3',
    rawText: 'Ride to a hospital appointment Saturday morning',
    category: 'ride',
    urgency: 'scheduled',
    timeWindow: 'Saturday morning',
    locationText: 'Near the park',
    preference: 'prefers same-gender helper',
    confidence: 0.86,
    location: offsetFrom(ANCHOR, 0.0072, -0.0086),
    status: 'open',
    matchedHelperId: null,
    aiMatchReason: null,
    createdAt: '2026-09-05T12:00:00Z',
    requesterConfirmed: false,
    helperConfirmed: false,
    customLabel: null,
  },
  {
    id: 'req-moving',
    requesterId: 'user-seed-4',
    rawText: 'Need help moving a few boxes two blocks over',
    category: 'moving_help',
    urgency: 'scheduled',
    timeWindow: 'Sunday afternoon',
    locationText: 'Residential streets nearby',
    preference: null,
    confidence: 0.88,
    location: offsetFrom(ANCHOR, -0.0034, -0.0098),
    status: 'open',
    matchedHelperId: null,
    aiMatchReason: null,
    createdAt: '2026-09-05T11:00:00Z',
    requesterConfirmed: false,
    helperConfirmed: false,
    customLabel: null,
  },
  {
    // Shows the open-ended path: a real need that fits none of the buckets.
    id: 'req-other',
    requesterId: 'user-seed-5',
    rawText:
      "My father passed and I don't know how to arrange a janazah. I need someone who has done this before to walk me through it.",
    category: 'other',
    urgency: 'immediate',
    timeWindow: 'today',
    locationText: 'Near the masjid',
    preference: null,
    confidence: 0.42,
    location: offsetFrom(ANCHOR, 0.0019, -0.0119),
    status: 'open',
    matchedHelperId: null,
    aiMatchReason: null,
    createdAt: '2026-09-05T16:10:00Z',
    requesterConfirmed: false,
    helperConfirmed: false,
    customLabel: 'Help arranging a janazah',
  },
];
