import type { HelpRequest, LatLng, Partner, User } from '@/types/barakah';

/** ICPC Paterson — 152 Derrom Ave area */
export const ICPC: LatLng = {
  latitude: 40.9177,
  longitude: -74.1404,
};

export const MAP_REGION = {
  ...ICPC,
  latitudeDelta: 0.035,
  longitudeDelta: 0.035,
};

export const PLACE_LOOKUP: { keys: string[]; location: LatLng; label: string }[] = [
  {
    keys: ['icpc', 'masjid', 'derrom', 'jummah', 'jumuah', 'mosque'],
    location: ICPC,
    label: 'Near ICPC, Derrom Ave',
  },
  {
    keys: ['main ave', 'main street', 'broadway'],
    location: { latitude: 40.9148, longitude: -74.162 },
    label: 'Near Main Ave',
  },
  {
    keys: ['eastside', 'east side park', 'park'],
    location: { latitude: 40.9125, longitude: -74.1355 },
    label: 'Near Eastside Park',
  },
  {
    keys: ['university', 'passaic', 'college', 'pccc'],
    location: { latitude: 40.9245, longitude: -74.148 },
    label: 'Near Passaic County CC area',
  },
];

export function geocodePlace(text: string): { location: LatLng; label: string } {
  const lower = text.toLowerCase();
  for (const entry of PLACE_LOOKUP) {
    if (entry.keys.some((k) => lower.includes(k))) {
      return { location: entry.location, label: entry.label };
    }
  }
  return {
    location: {
      latitude: ICPC.latitude + 0.002,
      longitude: ICPC.longitude - 0.003,
    },
    label: text.trim() || 'Near ICPC',
  };
}

export const DEFAULT_USER_ID = 'user-aisha';

export const partners: Partner[] = [
  {
    id: 'partner-icpc',
    name: 'Islamic Center of Passaic County',
    type: 'institution',
    categories: ['childcare', 'ride', 'food', 'elder_transport'],
    location: ICPC,
    standingOffer: null,
  },
  {
    id: 'partner-green-market',
    name: 'Green Market Grocer',
    type: 'business',
    categories: ['food'],
    location: { latitude: 40.9152, longitude: -74.1598 },
    standingOffer: 'Friday pantry pickup — bags ready after Asr',
  },
];

export const users: User[] = [
  {
    id: DEFAULT_USER_ID,
    name: 'Aisha Rahman',
    phone: '+1 (973) 555-0142',
    trustTier: 2,
    categoriesOffered: ['ride', 'food'],
    location: { latitude: 40.919, longitude: -74.143 },
    ratingAvg: 4.9,
    ratingCount: 12,
    points: 80,
    badges: ['first_help', 'five_helps'],
    completedHelps: 7,
    responseRate: 0.92,
    lastMatchAt: '2026-09-01T14:00:00Z',
    partnerId: null,
    avatarColor: '#5B7CFF',
    isNewHelper: false,
    verificationStatus: 'approved',
    availabilityLabel: 'Evenings & Friday midday',
    radiusMiles: 5,
  },
  {
    id: 'user-omar',
    name: 'Omar Hassan',
    phone: '+1 (973) 555-0198',
    trustTier: 2,
    categoriesOffered: ['ride', 'food', 'moving_help'],
    location: { latitude: 40.9165, longitude: -74.1388 },
    ratingAvg: 4.8,
    ratingCount: 28,
    points: 240,
    badges: ['first_help', 'five_helps', 'twenty_five'],
    completedHelps: 26,
    responseRate: 0.95,
    lastMatchAt: '2026-09-04T18:00:00Z',
    partnerId: null,
    avatarColor: '#3D5FE8',
    isNewHelper: false,
    verificationStatus: 'approved',
    availabilityLabel: 'Weekday afternoons & Jummah',
    radiusMiles: 6,
  },
  {
    id: 'user-fatima',
    name: 'Fatima Ali',
    phone: '+1 (973) 555-0110',
    trustTier: 3,
    categoriesOffered: ['childcare', 'ride', 'food'],
    location: { latitude: 40.9182, longitude: -74.1412 },
    ratingAvg: 5.0,
    ratingCount: 41,
    points: 0,
    badges: ['first_help', 'five_helps', 'twenty_five'],
    completedHelps: 40,
    responseRate: 0.98,
    lastMatchAt: '2026-09-03T12:00:00Z',
    partnerId: 'partner-icpc',
    avatarColor: '#3CB371',
    isNewHelper: false,
    verificationStatus: 'approved',
    availabilityLabel: 'ICPC volunteer roster',
    radiusMiles: 8,
  },
  {
    id: 'user-yusuf',
    name: 'Yusuf Khan',
    phone: '+1 (973) 555-0166',
    trustTier: 2,
    categoriesOffered: ['food', 'laptop'],
    location: { latitude: 40.914, longitude: -74.158 },
    ratingAvg: null,
    ratingCount: 0,
    points: 0,
    badges: [],
    completedHelps: 0,
    responseRate: 1,
    lastMatchAt: null,
    partnerId: 'partner-green-market',
    avatarColor: '#E8A23A',
    isNewHelper: true,
    verificationStatus: 'approved',
    availabilityLabel: 'Store hours',
    radiusMiles: 4,
  },
  {
    id: 'user-mariam',
    name: 'Mariam Noor',
    phone: '+1 (973) 555-0133',
    trustTier: 2,
    categoriesOffered: ['ride', 'moving_help'],
    location: { latitude: 40.921, longitude: -74.146 },
    ratingAvg: 4.6,
    ratingCount: 9,
    points: 90,
    badges: ['first_help', 'five_helps'],
    completedHelps: 9,
    responseRate: 0.88,
    lastMatchAt: '2026-08-28T10:00:00Z',
    partnerId: null,
    avatarColor: '#7B6CFF',
    isNewHelper: false,
    verificationStatus: 'approved',
    availabilityLabel: 'Weekends',
    radiusMiles: 5,
  },
  {
    id: 'user-ibrahim',
    name: 'Ibrahim Saleh',
    phone: '+1 (973) 555-0177',
    trustTier: 2,
    categoriesOffered: ['ride', 'food'],
    location: { latitude: 40.913, longitude: -74.136 },
    ratingAvg: 4.7,
    ratingCount: 15,
    points: 150,
    badges: ['first_help', 'five_helps'],
    completedHelps: 15,
    responseRate: 0.9,
    lastMatchAt: '2026-09-02T09:00:00Z',
    partnerId: null,
    avatarColor: '#2A9D8F',
    isNewHelper: false,
    verificationStatus: 'approved',
    availabilityLabel: 'Mornings',
    radiusMiles: 7,
  },
];

export const seedRequests: HelpRequest[] = [
  {
    id: 'req-jummah',
    requesterId: 'user-seed-1',
    rawText: 'Need a ride to Jummah tomorrow around 1pm, near ICPC',
    category: 'ride',
    urgency: 'scheduled',
    timeWindow: 'tomorrow 1pm–2pm',
    locationText: 'Near ICPC, Derrom Ave',
    preference: null,
    confidence: 0.94,
    location: { latitude: 40.9181, longitude: -74.141 },
    status: 'open',
    matchedHelperId: null,
    aiMatchReason: null,
    createdAt: '2026-09-05T14:00:00Z',
    requesterConfirmed: false,
    helperConfirmed: false,
  },
  {
    id: 'req-food',
    requesterId: 'user-seed-2',
    rawText: 'Could use groceries this evening near Main Ave, family of 4',
    category: 'food',
    urgency: 'immediate',
    timeWindow: 'this evening',
    locationText: 'Near Main Ave',
    preference: null,
    confidence: 0.9,
    location: { latitude: 40.915, longitude: -74.1605 },
    status: 'open',
    matchedHelperId: null,
    aiMatchReason: null,
    createdAt: '2026-09-05T15:30:00Z',
    requesterConfirmed: false,
    helperConfirmed: false,
  },
  {
    id: 'req-eastside',
    requesterId: 'user-seed-3',
    rawText: 'Ride to appointment near Eastside Park Saturday morning',
    category: 'ride',
    urgency: 'scheduled',
    timeWindow: 'Saturday morning',
    locationText: 'Near Eastside Park',
    preference: 'prefers same-gender helper',
    confidence: 0.86,
    location: { latitude: 40.9128, longitude: -74.1358 },
    status: 'open',
    matchedHelperId: null,
    aiMatchReason: null,
    createdAt: '2026-09-05T12:00:00Z',
    requesterConfirmed: false,
    helperConfirmed: false,
  },
  {
    id: 'req-moving',
    requesterId: 'user-seed-4',
    rawText: 'Need help moving a few boxes two blocks from Derrom Ave',
    category: 'moving_help',
    urgency: 'scheduled',
    timeWindow: 'Sunday afternoon',
    locationText: 'Residential streets off Derrom',
    preference: null,
    confidence: 0.88,
    location: { latitude: 40.9168, longitude: -74.1375 },
    status: 'open',
    matchedHelperId: null,
    aiMatchReason: null,
    createdAt: '2026-09-05T11:00:00Z',
    requesterConfirmed: false,
    helperConfirmed: false,
  },
];
